"use client";

import Editor from "@monaco-editor/react";

const PLACEHOLDER_TEX = `\\documentclass[12pt]{article}
\\usepackage[margin=1in]{geometry}
\\usepackage{amsmath, amssymb}
\\usepackage{enumitem}

\\title{Sample Question Paper}
\\author{Generated by Libra}
\\date{\\today}

\\begin{document}
\\maketitle

\\section*{Section A — Multiple Choice}

\\begin{enumerate}
  \\item What is the chemical formula for water?
  \\begin{enumerate}[label=(\\alph*)]
    \\item H\\textsubscript{2}O
    \\item CO\\textsubscript{2}
    \\item NaCl
    \\item O\\textsubscript{2}
  \\end{enumerate}
\\end{enumerate}

\\section*{Section B — Short Answer}

\\begin{enumerate}
  \\item Explain the process of photosynthesis. \\hfill [5 marks]
  \\item Define Newton's second law of motion. \\hfill [3 marks]
\\end{enumerate}

\\end{document}
`;

export default function CodeEditor() {
  return (
    <div className="h-full w-full bg-[#1e1e1e]">
      <Editor
        height="100%"
        defaultLanguage="plaintext"
        defaultValue={PLACEHOLDER_TEX}
        theme="vs-dark"
        path="document.tex"
        options={{
          readOnly: true,
          minimap: { enabled: false },
          fontSize: 13,
          fontFamily: "'Fira Code', 'Cascadia Code', Consolas, monospace",
          lineNumbers: "on",
          scrollBeyondLastLine: false,
          padding: { top: 12 },
          renderLineHighlight: "gutter",
          overviewRulerBorder: false,
          hideCursorInOverviewRuler: true,
          wordWrap: "on",
          scrollbar: {
            verticalScrollbarSize: 6,
            horizontalScrollbarSize: 6,
          },
        }}
        onMount={(_editor, monaco) => {
          monaco.editor.defineTheme("agent-dark", {
            base: "vs-dark",
            inherit: true,
            rules: [],
            colors: {
              "editor.background": "#1e1e1e",
              "editorGutter.background": "#1e1e1e",
              "editor.lineHighlightBackground": "#282828",
              "editorLineNumber.foreground": "#727272",
              "editorLineNumber.activeForeground": "#B3B3B3",
            },
          });
          monaco.editor.setTheme("agent-dark");
        }}
      />
    </div>
  );
}
